# Generated by Django 5.2.4 on 2025-10-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelbazar', '0002_contact_ordertracking_productstock_returnstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='totalAmount',
            field=models.FloatField(default=0.0),
        ),
    ]
