# Generated by Django 5.2.4 on 2025-10-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelbazar', '0004_otp_user_gender_user_location_lat_user_location_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
