# Generated by Django 5.2.4 on 2025-10-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelbazar', '0006_payment_remove_order_fname_remove_order_lname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
