# Generated by Django 5.2.4 on 2025-10-29 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelbazar', '0017_alter_contact_options_order_products_data_order_town_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pixelbazar.ordertracking'),
        ),
    ]
