# Generated by Django 5.2.4 on 2025-10-29 06:30

import django.db.models.deletion
import pixelbazar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelbazar', '0018_alter_order_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking',
            field=models.OneToOneField(default=pixelbazar.models.default_tracking, on_delete=django.db.models.deletion.CASCADE, to='pixelbazar.ordertracking'),
        ),
    ]
