# Generated by Django 5.2.4 on 2025-10-30 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelbazar', '0019_alter_order_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_returnable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='return_policy_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='product',
            name='return_policy_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('reason', models.CharField(choices=[('defective', 'Defective Product'), ('wrong_item', 'Wrong Item Delivered'), ('not_as_described', 'Not as Described'), ('damaged', 'Damaged in Transit'), ('size_issue', 'Size/Fit Issue'), ('quality_issue', 'Quality Issue'), ('changed_mind', 'Changed Mind'), ('other', 'Other')], max_length=20)),
                ('reason_description', models.TextField()),
                ('return_type', models.CharField(choices=[('refund', 'Refund'), ('exchange', 'Exchange')], default='refund', max_length=10)),
                ('status', models.CharField(choices=[('requested', 'Return Requested'), ('approved', 'Return Approved'), ('rejected', 'Return Rejected'), ('pickup_scheduled', 'Pickup Scheduled'), ('picked_up', 'Picked Up'), ('received', 'Return Received'), ('quality_check', 'Quality Check'), ('refund_initiated', 'Refund Initiated'), ('refund_completed', 'Refund Completed'), ('exchange_initiated', 'Exchange Initiated'), ('exchange_completed', 'Exchange Completed')], default='requested', max_length=20)),
                ('refund_amount', models.FloatField(blank=True, null=True)),
                ('processing_fee', models.FloatField(default=0.0)),
                ('pickup_address', models.TextField(blank=True, null=True)),
                ('pickup_date', models.DateTimeField(blank=True, null=True)),
                ('pickup_partner', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='pixelbazar.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
