# Generated by Django 5.2.4 on 2025-10-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelbazar', '0020_product_is_returnable_product_return_policy_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='free_delivery_days_left',
            field=models.IntegerField(default=2),
        ),
    ]
