# Generated by Django 5.2.4 on 2025-11-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelbazar', '0022_category_parent_category_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(choices=[('mobiles-tablets', 'Mobiles & Tablets'), ('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home-furniture', 'Home & Furniture'), ('tv-appliances', 'TV & Appliances'), ('beauty', 'Beauty'), ('food-grocery', 'Food & Grocery')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(blank=True, choices=[('mobiles-tablets', 'Mobiles & Tablets'), ('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home-furniture', 'Home & Furniture'), ('tv-appliances', 'TV & Appliances'), ('beauty', 'Beauty'), ('food-grocery', 'Food & Grocery')], max_length=50, null=True),
        ),
    ]
