# Generated by Django 5.2.4 on 2025-11-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelbazar', '0023_alter_category_options_category_display_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicbanner',
            name='image',
            field=models.ImageField(upload_to='music_banners/'),
        ),
    ]
