# Generated by Django 5.2.4 on 2025-11-10 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelbazar', '0024_alter_musicbanner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(choices=[('smartphones', 'Smartphones'), ('tablets', 'Tablets'), ('mobile-accessories', 'Mobile Accessories'), ('laptops', 'Laptops'), ('headphones', 'Headphones'), ('speakers', 'Speakers'), ('cameras', 'Cameras'), ('gaming', 'Gaming'), ('mens-clothing', "Men's Clothing"), ('womens-clothing', "Women's Clothing"), ('footwear', 'Footwear'), ('accessories', 'Accessories'), ('furniture', 'Furniture'), ('home-decor', 'Home Decor'), ('kitchen', 'Kitchen'), ('televisions', 'Televisions'), ('refrigerators', 'Refrigerators'), ('washing-machines', 'Washing Machines'), ('air-conditioners', 'Air Conditioners'), ('skincare', 'Skincare'), ('makeup', 'Makeup'), ('haircare', 'Haircare'), ('fruits-vegetables', 'Fruits & Vegetables'), ('dairy', 'Dairy'), ('snacks', 'Snacks'), ('music-instruments', 'Music Instruments'), ('audio-equipment', 'Audio Equipment')], max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories_list', to='pixelbazar.category')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pixelbazar.subcategory'),
        ),
    ]
